# Generated by Django 4.2.2 on 2023-07-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_link_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
