# Generated by Django 4.2.2 on 2023-07-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_activation_link_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_link_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
